apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color
  labels:
     
    app: simple-webapp

spec:
  containers:

    - name: simple-webapp-container
      image: mmumshad/simple-webapp-color

      env:
        - name: APP_COLOR
          value: "red"
      ports:
        - containerPort: 8080
       


