apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-nodeport-web
  name: service-nodeport-web
  namespace: production
spec:
  ports:
  - name: 8080-8080
    nodePort: 30008
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-webapp
  type: NodePort
status:
  loadBalancer: {}
